# ===============================
# APPLICATION
# ===============================
spring.application.name=hrms-saas-service

# ===============================
# SERVER
# ===============================
server.port=8081
server.servlet.context-path=/saas-service

# ===============================
# DATABASE (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/hrms
spring.datasource.username=postgres
spring.datasource.password=Sanjay@1312
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# HIKARI CP
# ===============================
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.pool-name=HikariPoolSaaS

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# DEFAULT SCHEMA
# ===============================
spring.jpa.properties.hibernate.default_schema=saas_db

# ===============================
# JPA PERFORMANCE
# ===============================
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# ===============================
# TIMEZONE
# ===============================
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jackson.time-zone=UTC

# ===============================
# LOGGING
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.security=DEBUG

# ===============================
# SWAGGER (SPRINGDOC)
# ===============================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.enabled=true
springdoc.packages-to-scan=com.hewhorizon.hrms.saas.controllers
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

# ===============================
# SECURITY (AUTH0 - RS256)
# ===============================
# IMPORTANT: Use ONLY issuer-uri (no secret-key)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-w0b6ytjc5pnjqndu.us.auth0.com/

# ===============================
# AUTH0 CUSTOM CONFIG (OPTIONAL)
# ===============================
auth0.domain=dev-w0b6ytjc5pnjqndu.us.auth0.com

# Your custom API identifier (MUST match audience used while fetching token)
auth0.audience=https://hrms-api

# Custom claim namespace (for tenantId etc.)
auth0.claim.namespace=https://hrms.com/